SetBoxWebUI/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace SetBoxWebUI.Controllers
{
    [Authorize]
    public class CompaniesController : BaseController
    {
        // GET: Companies
        public ActionResult Index()
        {
            return View();
        }

        // GET: Companies/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Companies/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Companies/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SetBoxWebUI/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using SetBoxWebUI.Helpers;
using SetBoxWebUI.Interfaces;
using SetBoxWebUI.Models;
using SetBoxWebUI.Models.Views;
using SetBoxWebUI.Repository;

namespace SetBoxWebUI.Controllers
{
    [Authorize]
    public class FilesController : BaseController
    {
        private readonly ILogger<FilesController> _logger;
        private readonly IRepository<FileCheckSum, Guid> _files;
        private readonly IRepository<Device, Guid> _devices;
        private readonly IRepository<FilesDevices, Guid> _fileDevice;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IServiceScopeFactory _serviceScopeFactory;

        /// <summary>
        /// FilesController
        /// </summary>
        public FilesController(ILogger<FilesController> logger, ApplicationDbContext context, IHostingEnvironment hostingEnvironment, IServiceScopeFactory serviceScopeFactory)
        {
            _logger = logger;
            _files = new Repository<FileCheckSum, Guid>(context);
            _devices = new Repository<Device, Guid>(context);
            _fileDevice = new Repository<FilesDevices, Guid>(context);
            _hostingEnvironment = hostingEnvironment;
            _serviceScopeFactory = serviceScopeFactory;
        }

      
        public async Task<GridPagedOutput<FileCheckSum>> List(GridPagedInput input)
        {
            try
            {
                if (string.IsNullOrEmpty(input.SearchPhrase))
                    input.SearchPhrase = "";


                Expression<Func<FileCheckSum, object>> orderby = o => o.CreationDateTime;
                var keys = input.Sort.OrderBy(kvp => kvp.Key).First();

                switch (keys.Key)
                {
                    case "name":
                        orderby = o => o.Name;
                        break;
                    case "description":
                        orderby = o => o.Description;
                        break;
                    case "extension":
                        orderby = o => o.Extension;
                        break;
                    case "size":
                        orderby = o => o.Size;
                        break;
                    case "creationDateTime":
                        orderby = o => o.CreationDateTime;
                        break;
                }

                var files = await _files.GetPagination(l => l.FileId.ToString() == input.Id
                                             || l.CreationDateTime.ToString("dd/MM/yyyy").Contains(input.SearchPhrase)
                                             || l.Name.Contains(input.SearchPhrase)
                                             || l.Path.Contains(input.SearchPhrase)
                                             || l.Extension.Contains(input.SearchPhrase),
                                         keys.Value == "asc" ? orderby : null,
                                         keys.Value == "desc" ? orderby : null,
                                         input.Current,
                                         input.RowCount);


                var item = new GridPagedOutput<FileCheckSum>(files.Value) { Current = input.Current, RowCount = input.RowCount, Total = files.Key };
                return item;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return null;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditOrNew(string id, string command)
        {
            try
            {
                ViewData["Command"] = command;
                var devices = await _devices.GetAsync();

                if (string.IsNullOrEmpty(id))
                {
                    ViewData["New"] = true;
                    return View("Index", new FilesViewModel()
                    {
                        AllDevices = devices.Select(x => new FileDeviceViewModel()
                        {
                            CompanyName = x.Company?.Name,
                            Id = x.DeviceId,
                            DeviceIdentifier = x.DeviceIdentifier,
                            DeviceName = x.Name
                        }).ToList(),
                        AllDeviceIds = string.Join(",", devices.Select(x => x.DeviceId.ToString()).ToList()),
                        IsNew = true,
                    });
                }
                var item = await _files.FirstOrDefaultAsync(x => x.FileId.ToString() == id);

                if (item == null)
                    throw new KeyNotFoundException($"DeviceId: {id} not found.");

                ViewData["Edit"] = true;

                var devicesFile = item.Devices.Select(x => x.Device);
                var idsRemove = devicesFile.Select(x => x.DeviceId);

                FilesViewModel model = new FilesViewModel
                {
                    IsEdited = command == "Edit",
                    IsNew = command == "New",
                    File = item,
                    Devices = devicesFile.Select(x => new FileDeviceViewModel()
                    {
                        CompanyName = x.Company?.Name,
                        Id = x.DeviceId,
                        DeviceIdentifier = x.DeviceIdentifier,
                        DeviceName = x.Name
                    }).ToList(),
                    DeviceIds = string.Join(",", devicesFile.Select(x => x.DeviceId.ToString()).ToList()),
                    AllDeviceIds = string.Join(",", devices.Where(x => !idsRemove.Contains(x.DeviceId))
                                            .Select(x => x.DeviceId.ToString()).ToList()),
                    AllDevices = devices.Where(x => !idsRemove.Contains(x.DeviceId))
                                        .Select(x => new FileDeviceViewModel()
                                        {
                                            CompanyName = x.Company?.Name,
                                            Id = x.DeviceId,
                                            DeviceIdentifier = x.DeviceIdentifier,
                                            DeviceName = x.Name
                                        }).ToList()
                };

                return View("Index", model);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                ViewData["Edit"] = false;
                ViewData["New"] = false;
                return View("Index", new FilesViewModel(ex));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(FilesViewModel u)
        {
            try
            {

                if (u.IsNew)
                {
                    if (u.fileToUpload == null)
                        u.fileToUpload = Request.Form.Files.FirstOrDefault();

                    if (u.fileToUpload == null)
                        throw new Exception("Favor selecionar um arquivo para upload.");

                    u.File.FileId = await Uploader(u.fileToUpload);
                }

                var ids = u.DeviceIds.Split(',');

                var file = await _files.FirstOrDefaultAsync(x => x.FileId == u.File.FileId);
                var devices = await _devices.GetAsync(x => ids.Contains(x.DeviceId.ToString()));

                if (file.Description != u.File.Description)
                {
                    file.Description = u.File.Description;
                    await _files.UpdateAsync(file);
                }

                var delsOld1 = await _fileDevice.GetAsync(x => x.FileId == u.File.FileId);
                await _fileDevice.DeleteRangeAsync(delsOld1);

                IList<FilesDevices> DevicesInFile = new List<FilesDevices>();

                foreach (var device in devices)
                {
                    DevicesInFile.Add(new FilesDevices()
                    {
                        FileId = file.FileId,
                        File = file,
                        Device = device,
                        DeviceId = device.DeviceId
                    });

                    device.LogAccesses.Add(new DeviceLogAccesses()
                    {
                        CreationDateTime = DateTime.Now,
                        Message = $"File {file.Name} Added",
                        IpAcessed = HttpContext.GetClientIpAddress()
                    });
                    await _devices.UpdateAsync(device);
                }

                if (DevicesInFile.Count > 0)
                {
                    await _fileDevice.AddRangeAsync(DevicesInFile);
                }

                return View("Index", new FilesViewModel("Data Updated successfully."));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return View("Index", new FilesViewModel(ex));
            }
        }


        public async Task<string> Delete(string id)
        {
            try
            {
                var delsDevicesFile = await _fileDevice.GetAsync(x => x.FileId.ToString() == id);
                var delsFile = await _files.FirstOrDefaultAsync(x => x.FileId.ToString() == id);

                if (delsFile == null)
                    return "File Not Found!";

                var deviceIds = delsDevicesFile.Select(x => x.DeviceId).ToList();
                string infoDel = $"File {delsFile.Name} deleted.";

                await _fileDevice.DeleteRangeAsync(delsDevicesFile);

SetBoxWebUI/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SetBoxWebUI.Interfaces;
using SetBoxWebUI.Models;
using SetBoxWebUI.Models.Views;
using SetBoxWebUI.Repository;

namespace SetBoxWebUI.Controllers
{
    [Authorize]
    public class SupportController : BaseController
    {
        private readonly ILogger<SupportController> _logger;
        private readonly IRepository<Support, Guid> _support;
        private readonly IRepository<Device, Guid> _devices;

        /// <summary>
        /// SetBoxController
        /// </summary>
        public SupportController(ILogger<SupportController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _support = new Repository<Support, Guid>(context);
            _devices = new Repository<Device, Guid>(context);
        }

        public async Task<IActionResult> Index()
        {
            var support = await _support.FirstOrDefaultAsync();

            if (support == null)
                return View(new SupportViewModel("") { SupportId = Guid.NewGuid() });

            return View(new SupportViewModel("")
            {
                SupportId = support.SupportId,
                Company = support.Company,
                Name = support.Name,
                Email = support.Email,
                Telephone = support.Telephone
            });


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(SupportViewModel s)
        {
            s.Title = "";
            s.Mensage = "";

            if (ModelState.IsValid) //verifica se é válido
            {
                try
                {
                    var support = await _support.FirstOrDefaultAsync();
                    bool isNew = false;

                    if (support == null)
                    {
                        isNew = true;
                        support = new Support
                        {
                            SupportId = Guid.NewGuid()
                        };
                    }

                    support.Company = s.Company;
                    support.Email = s.Email;
                    support.Name = s.Name;
                    support.Telephone = s.Telephone;
                    support.CreationDateTime = DateTime.Now;

                    if (isNew)
                        await _support.AddAsync(support);
                    else
                        await _support.UpdateAsync(support);

                    s.SupportId = support.SupportId;


                    var devices = await _devices.GetAsync();

                    foreach (var device in devices)
                    {

                        device.Support = await _support.FirstOrDefaultAsync();

                        if (device.LogAccesses == null)
                            device.LogAccesses = new List<DeviceLogAccesses>();

                        device.LogAccesses.Add(new DeviceLogAccesses()
                        {
                            CreationDateTime = DateTime.Now,
                            DeviceLogAccessesId = Guid.NewGuid(),
                            IpAcessed = HttpContext.GetClientIpAddress(),
                            Message = "Device Support Update!"
                        });

                    }

                    await _devices.UpdateRangeAsync(devices);

                    s.Title = "Success";
                    s.Mensage = "Update was successful.";
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, ex.Message);
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View(s);
        }
    }
}

SetBoxWebUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationIdentityUser> SignInManager
@inject UserManager<ApplicationIdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewData["Title"] - SetBoxWebUI</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>

    <link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/animate/animate.css">
    <link rel="stylesheet" type="text/css" href="~/lib/css-hamburgers/hamburgers.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/perfect-scrollbar/perfect-scrollbar.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/animsition/css/animsition.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/select2/select2.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" type="text/css" href="~/lib/jquery-bootgrid/jquery.bootgrid.min.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap-slider/bootstrap-slider.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/glyphicons.css" />
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />

    @RenderSection("header", required: false)
</head>
<body>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>

    <script src="~/lib/animsition/js/animsition.min.js"></script>
    <script src="~/lib/bootstrap-slider/bootstrap-slider.min.js"></script>
    <script src="~/lib/jquery-mask/jquery.mask.min.js"></script>
    <script src="~/lib/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="~/lib/select2/select2.min.js"></script>
    <script src="~/lib/daterangepicker/moment.min.js"></script>
    <script src="~/lib/daterangepicker/daterangepicker.js"></script>
    <script src="~/lib/countdowntime/countdowntime.js"></script>
    <script src="~/lib/bootbox/bootbox.all.min.js"></script>
    <script src="~/lib/bootbox/bootbox.locales.min.js"></script>
    <script src="~/lib/jquery-bootgrid/jquery.bootgrid.min.js"></script>
    <script src="~/lib/jquery-bootgrid/jquery.bootgrid.fa.min.js"></script>
    <script src="~/lib/bootstrap-slider/bootstrap-slider.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

    @if (SignInManager.IsSignedIn(User))
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SetBoxWebUI</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Devices" asp-action="Index">Devices</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Files" asp-action="Index">Files</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Companies</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Support" asp-action="Index">Support</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="/swagger">API</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    }
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @if (SignInManager.IsSignedIn(User))
    {
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - SetBoxWebUI - Afonsoft
            </div>
        </footer>
    }

    <div id="pleaseWait" data-backdrop="static" data-keyboard="false" style="position: fixed; z-index: 999; height: 100%; width: 100%; top: 0; left: 0; background-color: Black; filter: alpha(opacity=60); opacity: 0.6; -moz-opacity: 0.8;">
        <div id="loader"></div>
    </div>

</body>
</html>